name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        compiler: [g++, clang++]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up CMake and Ninja
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: latestrc
        ninjaVersion: latest
      
    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -G Ninja -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
        ninja
    
    - name: Test
      run: |
        cd build
        ./BigNumTest