name: C/C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        compiler: [g++, clang++]
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@latest

    - name: Setup CMake and Ninja
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: latestrc
        ninjaVersion: latest
      
    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -G Ninja -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
        ninja
    
    - name: Test
      run: |
        cd build
        ./BigNumTest